M48
; DRILL file {KiCad (6.0.5)} date Mon May 30 11:03:14 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-30T11:03:14+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.2126Y-3.5039
X4.2126Y-4.3701
X5.2756Y-3.5039
X5.2756Y-4.3701
T0
M30
